INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/intro.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /form/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/someshs/GitHub/csal/dynamic_form/form/intro.py", line 128, in intro_survey
    logging.info(vars(form.seen_brands))
AttributeError: 'SurveyForm' object has no attribute 'seen_brands'
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/intro.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /form/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/someshs/GitHub/csal/dynamic_form/form/intro.py", line 139, in intro_survey
    return render(request, "introduction.html", {"form": form})
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 28: 'endfor'. Did you forget to register or load this tag?
ERROR:django.request:Internal Server Error: /form/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/defaulttags.py", line 1027, in find_library
    return parser.libraries[name]
KeyError: 'numsplit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/someshs/GitHub/csal/dynamic_form/form/intro.py", line 139, in intro_survey
    return render(request, "introduction.html", {"form": form})
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/defaulttags.py", line 1089, in load
    lib = find_library(parser, name)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/defaulttags.py", line 1029, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'numsplit' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
cache
i18n
import_export_tags
l10n
log
socialaccount
static
tz
widget_tweaks
ERROR:django.request:Internal Server Error: /form/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/defaulttags.py", line 1027, in find_library
    return parser.libraries[name]
KeyError: 'numsplitter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/someshs/GitHub/csal/dynamic_form/form/intro.py", line 139, in intro_survey
    return render(request, "introduction.html", {"form": form})
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/defaulttags.py", line 1089, in load
    lib = find_library(parser, name)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/template/defaulttags.py", line 1029, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'numsplitter' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
cache
i18n
import_export_tags
l10n
log
socialaccount
static
tz
widget_tweaks
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/intro.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/intro.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/intro.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/intro.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/intro.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
INFO:root:4
INFO:root:4
INFO:root:4
INFO:root:4
INFO:root:4
INFO:root:4
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
INFO:root:4
INFO:root:4
INFO:root:4
INFO:root:4
INFO:root:4
INFO:root:4
ERROR:django.request:Internal Server Error: /form/brand/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/someshs/GitHub/csal/dynamic_form/form/questions.py", line 209, in brand_survey
    return render(request, "brand_survey.html", {"form": curr_form, "brand": brand})
UnboundLocalError: local variable 'curr_form' referenced before assignment
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
ERROR:django.request:Internal Server Error: /form/brand/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/someshs/GitHub/csal/dynamic_form/form/questions.py", line 206, in brand_survey
    return render(request, "brand_survey.html", {"form": curr_form, "brand": brand})
UnboundLocalError: local variable 'curr_form' referenced before assignment
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:4
ERROR:django.request:Internal Server Error: /form/brand/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view form.questions.brand_survey didn't return an HttpResponse object. It returned None instead.
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:3
INFO:root:3
ERROR:django.request:Internal Server Error: /form/brand/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view form.questions.brand_survey didn't return an HttpResponse object. It returned None instead.
INFO:django.utils.autoreload:/Users/someshs/GitHub/csal/dynamic_form/form/questions.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:3
ERROR:django.request:Internal Server Error: /form/brand/
Traceback (most recent call last):
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/someshs/GitHub/csal/dynamic_form/form/questions.py", line 196, in brand_survey
    form.save()
  File "/Users/someshs/GitHub/csal/csal/lib/python3.9/site-packages/django/forms/models.py", line 539, in save
    raise ValueError(
ValueError: The RememberedBrand could not be created because the data didn't validate.
